name: asimov-cli
base: core22
version: '25.0.0-dev.2'
summary: Asimov CLI Snap
description: |
  Bundles a prebuilt Asimov CLI binary (gzipped) into a snap.

grade: devel
confinement: strict

parts:
  asimov-cli:
    plugin: dump
    source: https://github.com/asimov-platform/asimov-cli/releases/download/25.0.0-dev.2/asimov-linux-x86.gz

    override-build: |
      # 1) Let Snapcraft download the file
      snapcraftctl pull

      # 2) Decompress the single .gz
      gunzip asimov-linux-x86.gz
      chmod +x asimov-linux-x86

      # 3) Move it into the snap so the final binary is at "bin/asimov-cli"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/bin"
      mv asimov-linux-x86 "$SNAPCRAFT_PART_INSTALL/bin/asimov-cli"

      # 4) Continue the normal dump process
      snapcraftctl build

apps:
  asimov-cli:
    command: bin/asimov-cli
