name: Pacman build & test

on:
  push:

jobs:
  build-pacman:
    runs-on: ubuntu-latest  # Use Arch Linux container
    container: archlinux:latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Required Packages
        run: |
          pacman -Sy --noconfirm base-devel git wget
          useradd -m builder  # Create a new non-root user
          chown -R builder /tmp/build  # Give ownership to builder user

      - name: Prepare Build Directory
        run: |
          mkdir -p /tmp/build
          cp -r pacman/* /tmp/build/
          ls -la /tmp/build
          chown -R builder /tmp/build  # Ensure builder has permissions

      - name: Build Pacman Package
        run: |
          cd /tmp/build
          sudo -u builder makepkg -si --noconfirm  # Run as non-root user

      - name: Upload Pacman Artifact
        uses: actions/upload-artifact@main
        with:
          name: asimov-cli-pkg
          path: "/tmp/build/*.pkg.tar.zst"

      - name: Install Built Package
        run: |
          pacman -U --noconfirm /tmp/build/*.pkg.tar.zst  # Install as root

      - name: Verify Installation (asimov --version)
        run: |
          asimov --version
