name: Pacman build & test

on:
  push:

jobs:
  build-pacman:
    runs-on: ubuntu-latest  # Use Arch Linux container
    container:
      image: archlinux:latest
      options: --user root  # Run as root to allow pacman installation

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Required Packages
        run: |
          pacman -Sy --noconfirm base-devel git wget

      - name: Prepare Build Directory
        run: |
          mkdir -p /tmp/build
          cp -r pacman/* /tmp/build/
          ls -la /tmp/build

      - name: Build Pacman Package
        run: |
          cd /tmp/build
          chmod -R 777 /tmp/build  # Ensure it is writable
          makepkg -si --noconfirm  # Run as root, no sudo required

      - name: Upload Pacman Artifact
        uses: actions/upload-artifact@main
        with:
          name: asimov-cli-pkg
          path: "/tmp/build/*.pkg.tar.zst"

      - name: Install Built Package
        run: |
          pacman -U --noconfirm /tmp/build/*.pkg.tar.zst  # No sudo required

      - name: Verify Installation (asimov --version)
        run: |
          asimov --version
