name: Build and Publish Pacman Package

on:
  push:

jobs:
  build:
    name: Build Pacman Package
    runs-on: ubuntu-latest
    container: archlinux:latest  # Use Arch Linux container

    steps:
      - name: Create Non-Root User for Makepkg
        run: |
          pacman -Sy --noconfirm base-devel git
          useradd -m builduser
          passwd -d builduser
          echo 'builduser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          chown -R builduser /github/workspace

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Version from Release
        run: echo "PKG_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Build Pacman Package as Non-Root User
        run: sudo -u builduser makepkg -s --noconfirm

      - name: Upload Built Package
        uses: actions/upload-artifact@v4
        with:
          name: asimov-cli-pacman
          path: "*.pkg.tar.zst"


  test-install:
    name: Test Pacman Installation
    needs: build
    runs-on: ubuntu-latest
    container: archlinux:latest  # Use Arch Linux container

    steps:
      - name: Update Pacman and Install Git
        run: pacman -Sy --noconfirm git

      - name: Download Built Package
        uses: actions/download-artifact@v4
        with:
          name: asimov-cli-pacman

      - name: Install the Package
        run: pacman -U --noconfirm *.pkg.tar.zst

      - name: Verify Installation
        run: asimov --version

  publish-repo:
    name: Publish to Pacman Repo
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Built Package
        uses: actions/download-artifact@v4
        with:
          name: asimov-cli-pacman

      - name: Create Pacman Repository
        run: |
          mkdir -p repo
          mv *.pkg.tar.zst repo/
          repo-add repo/myrepo.db.tar.gz repo/*.pkg.tar.zst

      - name: Upload Repo to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: repo
