name: Test Flatpak

on: [push]

jobs:
  build-and-test-flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Flatpak and Flatpak Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Setup Flatpak environment
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak update -y
          sudo flatpak install -y flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08

      - name: Build the Flatpak
        run: |
          ls -l flatpak
          flatpak-builder --force-clean build-dir flatpak/com.asimov_platform.asimov_cli.yaml

      - name: Install and Test the CLI
        run: |
          flatpak-builder --user --install --force-clean build-dir flatpak/com.asimov_platform.asimov_cli.yaml
          
          # Debug: Check installed files inside Flatpak
          flatpak run --command=sh com.asimov_platform.asimov_cli -c "ls -l /app/bin"

          # Debug: Ensure the binary exists and is executable
          flatpak run --command=sh com.asimov_platform.asimov_cli -c "file /app/bin/asimov"
          flatpak run --command=sh com.asimov_platform.asimov_cli -c "chmod +x /app/bin/asimov"

          # Correctly execute the binary
          flatpak run --command=/app/bin/asimov com.asimov_platform.asimov_cli --version
