name: Homebrew Test

on: [push, workflow_dispatch]

jobs:
  brew-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Tap the Homebrew Repository
        run: brew tap AlexSanchest/test https://github.com/AlexSanchest/homebrew-test.git

      - name: Install Formula
        run: brew install AlexSanchest/test/asimov-cli

      - name: Test Installed Binary
        run: asimov-cli --version
