name: Multi-OS Testing

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-13, macos-14 ]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Print environment
        run: |
          echo "Running on OS = ${{ matrix.os }}"
          uname -a

      - name: Build and test
        run: |
          echo "Put your build and test commands here."
          # Example:
          # npm install
          # npm test
