name: Test Homebrew Tap

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-tap:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-latest, macos-13, macos-14, macos-latest ]

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      # ---------------------------
      # Ubuntu 22.04
      # ---------------------------
      - name: Install & test on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git

          # Install Homebrew (Linuxbrew)
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

          # Load Homebrew into the current shell session
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          # Check brew
          brew --version

          # Tap your repo
          brew tap AlexSanches1/test

          # Install the CLI from the tap
          brew install asimov-cli

          # Verify the installed CLI
          asimov --version

      # ---------------------------
      # macOS 13 & macOS 14
      # ---------------------------
      - name: Install & test on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          # Homebrew is already available on GitHub's macOS runners
          brew --version

          # Tap your repo
          brew tap AlexSanches1/test

          # Install the CLI from the tap
          brew install asimov-cli

          # Verify the installed CLI
          asimov --version
