name: Nix CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-nix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      # Install Nix on Linux
      - name: Install Nix (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          curl -L https://nixos.org/nix/install | sh
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix --version

      # Install Nix on macOS
      - name: Install Nix (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          sh <(curl -L https://nixos.org/nix/install) --daemon
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          nix --version

      # Build & install from the local flake
      - name: Install from local flake
        shell: bash
        run: |
          # If on Linux, source the same profile again (to be sure)
          [ -f /home/runner/.nix-profile/etc/profile.d/nix.sh ] && source /home/runner/.nix-profile/etc/profile.d/nix.sh

          # Install the default package in flake.nix from the current repo
          nix profile install .

      # Verify the CLI
      - name: Check asimov
        shell: bash
        run: |
          asimov --version
