name: Test Flatpak

on:
  push:

jobs:
  build-and-test-flatpak:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Flatpak and Flatpak Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Build the Flatpak
        run: |
          ls -l flatpak
          flatpak-builder --force-clean build-dir flatpak/com.asimov_platform.asimov_cli.yaml

      - name: Install and Test the CLI
        run: |
          # Install the Flatpak into the current user's Flatpak installation
          flatpak-builder --user --install --force-clean build-dir flatpak/com.asimov_platform.asimov_cli.yaml
          
          # Now spawn a shell INSIDE the Flatpak sandbox and run "asimov --version"
          # This ensures the command "asimov --version" appears directly in logs
          flatpak run com.asimov_platform.asimov_cli sh -c 'asimov --version'
