name: Test Flatpak

on:
#  push:
#    branches:
#      - '**'
  pull_request:

jobs:
  build-and-test-flatpak:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Configuration
        run:
          flatpak remote-add --if-not-exists asimov-cli https://github.com/AlexSanches1/homebrew-test/tree/main/flatpak

      - name: Installation
        run: |
          flatpak install -y asimov-cli com.asimov_platform.asimov_cli

          flatpak run com.asimov_platform.asimov_cli --version
