name: Nix CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test-nix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      # ------------------------
      # Install Nix on Ubuntu
      # ------------------------
      - name: Install Nix (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          # Install Nix
          curl -L https://nixos.org/nix/install | sh
          
          # Enable flakes in the Nix config
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
          
          # Show version
          source /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix --version

      # ------------------------
      # Install Nix on macOS
      # ------------------------
      - name: Install Nix (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          # Install Nix in daemon mode
          sh <(curl -L https://nixos.org/nix/install) --daemon
          
          # Enable flakes in the Nix config
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
          
          # Show version
          source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          nix --version

      # ------------------------
      # Install & check asimov in one step
      # ------------------------
      - name: Install from local flake & check
        shell: bash
        run: |
          # Source Nix if on Ubuntu
          if [ -f /home/runner/.nix-profile/etc/profile.d/nix.sh ]; then
            source /home/runner/.nix-profile/etc/profile.d/nix.sh
          fi
          # Source Nix if on macOS
          if [ -f /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
            source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          fi

          # Install the default package from flake.nix in this repo
          nix profile install .

          # Confirm the CLI is installed and on PATH
          asimov --version
