name: Simple GitHub Action

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run a simple script
        run: |
          echo "Hello, world!"
          echo "This is a simple GitHub Action."
