name: Homebrew Test

on: [push, workflow_dispatch]

jobs:
  brew-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - - name: Tap the Homebrew Repository
        run: |
          brew untap AlexSanches1/homebrew-test || true
          brew tap AlexSanches1/homebrew-test https://github.com/AlexSanches1/homebrew-test.git --force-auto-update



      - name: Install Formula
        run: brew install AlexSanches1/test/asimov-cli

      - name: Test Installed Binary
        run: asimov-cli --version
